import { css } from "../../../styled-system/css";

export const root = css({
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  gap: "inline",
  minH: "targetMin",
  px: "3",
  fontFamily: "mono",
  fontSize: "sm",
  fontWeight: "semibold",
  lineHeight: "snug",
  borderWidth: "default",
  borderStyle: "solid",
  borderColor: "border.default",
  borderRadius: "none",
  cursor: "pointer",
  transitionProperty: "transform, background-color, color",
  transitionDuration: "snap",
  transitionTimingFunction: "stepSnap",
  _hover: { transform: "translate(3px, 3px)" },
  _focusVisible: { layerStyle: "focusRing" },
  _disabled: { opacity: "disabled", cursor: "not-allowed", _hover: { transform: "none" } },
  "@media (prefers-reduced-motion: reduce)": {
    transitionDuration: "instant",
    _hover: { transform: "none" },
  },
  '&[data-variant="solid"]': {
    bg: "accent.solid",
    color: "fg.onSolid",
    borderColor: "accent.solid",
    _hover: { bg: "accent.solidHover" },
  },
  '&[data-variant="outline"]': { bg: "transparent", color: "fg.default" },
  '&[data-variant="danger"]': {
    bg: "danger.solid",
    color: "fg.onDanger",
    borderColor: "danger.solid",
    _hover: { bg: "danger.solidHover" },
  },
  '&[data-size="icon"]': {
    w: "targetMin",
    h: "targetMin",
    minW: "targetMin",
    minH: "targetMin",
    px: "0",
    gap: "0",
    _hover: { transform: "translate(2px, 2px)" },
    "@media (prefers-reduced-motion: reduce)": { _hover: { transform: "none" } },
  },
});
